name: Move Test


on: [push, pull_request]


jobs:
test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Install Move
run: |
sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
# інструкції по інсталяції Move можуть змінюватися; тут — приклад.
- name: Run tests
run: ./scripts/run-tests.sh
